# Database connection.
# When Slacker is executed, it will attempt to connect to this database.

# Replace the following with your connection information.
# Note that at this point Slacker only works with SQL Server authentication.

server: mssql
database: tempdb # change the database name to your test database
user: sa
password: Yukon900
port: 1433
driver: tiny_tds