version: '3'
services:
  slacker:
    build: .
    depends_on: 
      - mssql
    # command: ["./wait-for-it.sh", "mssql:1433", "--", "./runner.sh"]
    command: ["tail", "-f", "/dev/null"] # make slacker container up and running
    container_name: slacker_sample
  mssql:
    container_name: mssql_sample
    image: microsoft/mssql-server-linux:latest
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Yukon900"
      ACCEPT_EULA: "Y"